### ISSUE TITLE
[by-design] repeater cell doesn't shrink

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#169]
When you move some elements inside repeater cell, borders are stretched. But when you move object back to the original position, borders are _not_ shrunk back. Only gap increases.

By the way, you can isolate repeater cell, during editing (maybe optionally) and apply new repeater options (new cell size) when user exists repeater mode.

**Comment by defr0zen** [comment]
This is by design. Otherwise, imagine that you are editing a cell in 3rd column. If the gaps shrink after you resize something, then the element will "run away" from the mouse. Which is quite annoying. Therefore the gaps increase to keep everything as is visually.
Don't think it's a big problem to re-adjust the gaps afterwards. Adobe XD, btw, works similarly.

**Comment by Boorj** [comment]
ok, so feel free to close this issue if it's intended.
