### ISSUE TITLE
[bug] (or feature request) Keep relations between text elements in repeater

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#172]
#### is it a bug or "feature" ?
- make a button (rectangle and text)
- make repeater
- edit text in all rep. cells.

And..
Now you can't set **text adjustment (text align)** to all text fields. So you need to select each text field and set adjustment manually. Relation is broken.

**Comment by defr0zen** [comment]
How do you set text adjustment? By double-clicking text first? Or by selecting the text element?
The difference is that if you edit the text (double click or use text tool), then you are changing the *content*, not the *font* of the element. For example, you can make the second word bold, change the color of the word, etc. Such changes are not repeatable.

**Comment by Boorj** [comment]
i was speaking only about adjustment 
![image](https://user-images.githubusercontent.com/2145313/29750840-24f3c6d6-8b71-11e7-9da0-fa160a88d843.png)

by the way, i don't know, whether it's intended or not, but when you select some text inside text block and adjust (right adjustment for example), it adjusts only this cell. But when you select whole text block, it adjusts same blocks in all cells.

**Comment by defr0zen** [comment]
> by the way, i don't know, whether it's intended or not

This is exactly what I meant. Editing *content* is not repeatable. Editing an entire text block is.
Double-clicking the text and making adjustments counts as editing *content*, because you are changing styles of text ranges (even when all text is selected, you are changing the style of a range). And text ranges are different in each cell. 

Not sure if it makes sense to analyze what changes you are making to the ranges and decide which ones to repeat and which not.

**Comment by Boorj** [comment]
okay.
Probably you could add a button "select same object in all repeater cells" and this will help a lot. It will add an ability for simultaneous editing all objects, or resetting its' properties.

**Comment by defr0zen** [comment]
we'll probably make it so that if you select *all text* with the *same formatting* and change a font property, it will count as changing font, not content. Then such change will be repeated.
But if you have for example text like:
> Your **text** _here_
And then you select all and change font size, then this will not be repeated. Because formatting of "text" or "here" could be different in other cells...
It's complex, as you see.

**Comment by Boorj** [comment]
yes, i see. 
Still, function *select same object in all cells* is a quite useful function (!). Saying this after working in project)

**Comment by defr0zen** [comment]
Done as described - when entire text is selected in the edit mode, font changes are propagated to element, and then to similar elements in other repeater cells.
