### ISSUE TITLE
[bug] coordinates / size jump

### ISSUE THREAD

**Issue by Boorj** [CarbonDesigns/carbon-ui#359]
no repro for that, but that's what i was doing:
- created circle to draw that round button. grey filled circle was created
- changed (by `shift + x`) fill and stroke. 
- set stroke to white
- started changing stroke width by keyboard, pressing `up`
= circle jumped to other coordinates and got size of artboard (375 × 667)
![image](https://user-images.githubusercontent.com/2145313/31852089-f34ec184-b69b-11e7-9ec9-ed0dc0a38e97.png)

**Comment by Boorj** [comment]
the story continues:
where's that circle in layers? 
![2017-10-21_20-17-47](https://user-images.githubusercontent.com/2145313/31852163-31b66728-b69d-11e7-8372-a335a670c9d3.gif)

**Comment by Boorj** [comment]
looks like #363 causes the original problem

**Comment by defr0zen** [comment]
Yes, jumping was caused by #363 and it is fixed. The circle is probably somehow not on the artboard (above it but not inside it), therefore it is not shown.
We'll try to better detect when the element must belong to an artboard. For example, we miss a case when you place an element outside and then move it with arrow keys over the artboard...

**Comment by defr0zen** [comment]
Regarding "invisible" image, it's hard to see on the gif without properties.

**Comment by Boorj** [comment]
> The circle is probably **somehow** not on the artboard (above it but not inside it), therefore it is not shown.
Okay, i suppose it was one of those cases that you will fix.
